### ISSUE TITLE
Serverside broken

### ISSUE THREAD

**Issue by TheRealM18** [BeetoGuy/LevelUp#13]
When I try to launch it with the server it tell me:

java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
	at levelup2.items.ItemOreChunk.getOreName(ItemOreChunk.java:46)
	at levelup2.items.ItemOreChunk.func_77653_i(ItemOreChunk.java:36)
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:515)
	at net.minecraft.item.ItemStack.func_151000_E(ItemStack.java:929)
	at net.minecraft.stats.StatList.func_75925_c(StatList.java:202)
	at net.minecraft.stats.StatList.reinit(StatList.java:348)
	at net.minecraftforge.common.ForgeModContainer.mappingChanged(ForgeModContainer.java:525)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:252)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:230)
	at net.minecraftforge.fml.common.Loader.fireRemapEvent(Loader.java:1083)
	at net.minecraftforge.fml.common.registry.PersistentRegistryManager.injectSnapshot(PersistentRegistryManager.java:363)
	at net.minecraftforge.fml.common.FMLContainer.readData(FMLContainer.java:329)
	at net.minecraftforge.fml.common.FMLCommonHandler.handleWorldDataLoad(FMLCommonHandler.java:418)
	at net.minecraft.world.storage.SaveFormatOld.loadAndFix(SaveFormatOld.java:119)
	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:122)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:228)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:267)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.I18n
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 28 more

**Comment by BeetoGuy** [comment]
Already reported on the Level Up! 2 repo here: https://github.com/BeetoGuy/LevelUp2/issues/1
